/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janela;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import principal.Cliente;
import principal.Gerenciador;
import principal.Vaga;
import principal.Veiculo;

/**
 *
 * @author Lucas-PC
 */
public class JanelaPrincipal extends javax.swing.JFrame {
	
	
	Gerenciador gerenciador = new Gerenciador();
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();

        initOtherComponents();
    }

    private void initOtherComponents() {
  		ActionListener cbClienteExistenteListener = new ActionListener() {
  		      public void actionPerformed(ActionEvent actionEvent) {
  		        clienteExistenteActionPerformed();
  		      }
  		};
  		cbClienteExistente.addActionListener(cbClienteExistenteListener);
  		
  		//action listener para o check box veiculo já é cadastrado
  		ActionListener cbVeiculoExistenteListener = new ActionListener() {
  		      public void actionPerformed(ActionEvent actionEvent) {
  		        veiculoExistenteActionPerformed();
  		      }
  		};
  		cbVeiculoExistente.addActionListener(cbVeiculoExistenteListener);
  		
  		//action listener para botao de procurar cliente
  		ActionListener btProcuraClienteListener = new ActionListener() {
  		      public void actionPerformed(ActionEvent actionEvent) {
  		        procuraClienteExistente();
  		      }
  		};
  		
  		btProcuraCliente.addActionListener(btProcuraClienteListener);
  		
  		
  		ActionListener btProcuraVeiculoListener = new ActionListener() {
  		      public void actionPerformed(ActionEvent actionEvent) {
  		        procuraVeiculoExistente();
  		      }
  		};
  		
  		btProcuraVeiculo.addActionListener(btProcuraVeiculoListener);
  		
  		for(Vaga vaga : gerenciador.getEstacionamento().getListaVagas())
  			listaTabelaGui.add(vaga);
		
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaTabelaGui = new janela.TabelaView();
        btSolicitaVaga = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaVagas = new javax.swing.JTable();
        btSolicitaLavaRapido = new javax.swing.JButton();
        btSolicitaOrcamento = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSolicitaVaga.setText("Solicitar Nova Vaga");
        btSolicitaVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolicitaVagaActionPerformed(evt);
            }
        });

        jTabelaVagas.setModel(listaTabelaGui);
        jScrollPane2.setViewportView(jTabelaVagas);

        btSolicitaLavaRapido.setText("Solicitar Lava Rápido");
        btSolicitaLavaRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolicitaLavaRapidoActionPerformed(evt);
            }
        });

        btSolicitaOrcamento.setText("Solicitar Orçamento");
        btSolicitaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolicitaOrcamentoActionPerformed(evt);
            }
        });

        jButton4.setText("Solicitar lava-rapido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Solicita pagamento");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btSolicitaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btSolicitaLavaRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btSolicitaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSolicitaVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSolicitaLavaRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSolicitaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSolicitaVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolicitaVagaActionPerformed
        cadastrarVeiculoCliente();
    }//GEN-LAST:event_btSolicitaVagaActionPerformed

    private void btSolicitaLavaRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolicitaLavaRapidoActionPerformed
        new JanelaLavaRapido();
    }//GEN-LAST:event_btSolicitaLavaRapidoActionPerformed

    private void btSolicitaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolicitaOrcamentoActionPerformed
        new JanelaOrcamento();
    }//GEN-LAST:event_btSolicitaOrcamentoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    	new JanelaLavaRapido();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new JanelaSolicitaPagamento();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSolicitaLavaRapido;
    private javax.swing.JButton btSolicitaOrcamento;
    private javax.swing.JButton btSolicitaVaga;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaVagas;
    private janela.TabelaView listaTabelaGui;
    // End of variables declaration//GEN-END:variables
    
    
    // Variaveis da tela cadastrar cliente
	private static int alturaJanela = 728; // seto a altura e largura da janela;
	private static int larguraJanela = 1024;
	
	private JButton btCadastrar = new JButton("Cadastrar");
	private JButton btProcuraCliente = new JButton("Procurar Cliente");
	private JButton btProcuraVeiculo = new JButton("Procurar Veiculo");
	
	private JLabel labelDadosPessoais = new JLabel("Dados pessoas");
	private JLabel labelDadosVeiculo = new JLabel("Dados do veículo");
	private JLabel lbNome = new JLabel("Digite o Nome:");
	private JLabel lbCpf = new JLabel("Digite o CPF:");
	private JLabel lbEmail = new JLabel("Email:");
	private JLabel lbNumTel = new JLabel("Telefone:");
	private JLabel lbClienteExiste = new JLabel("Digite o CPF do cliente cadastrado:");
	
	private JLabel lbModelo = new JLabel("Modelo:");
	private JLabel lbCor = new JLabel("Cor:");
	private JLabel lbPlaca = new JLabel("Placa:");
	private JLabel lbVeiculoExiste = new JLabel("Digite a placa do veiculo cadastrado:");
	private JLabel lbTamanho = new JLabel("Tamanho:");
	private JLabel lbAvarias = new JLabel("Avarias:");
	private JLabel lbProcuraCliente = new JLabel();
	private JLabel lbProcuraVeiculo = new JLabel();
	
	
	private JTextField tfNome = new JTextField(20);
	private JTextField tfCpf = new JTextField(20);
	private JTextField tfEmail = new JTextField(20);
	private JTextField tfNumTel = new JTextField(20);
	private JTextField tfClienteExistente = new JTextField(20);
	
	private JTextField tfCpfClienteExistente = new JTextField(20);
	private JCheckBox cbClienteExistente = new JCheckBox("Cliente cadastrado");
	private JCheckBox cbVeiculoExistente = new JCheckBox("Veiculo cadastrado");
	
	private JTextField tfModelo = new JTextField(20);
	private JTextField tfCor = new JTextField(20);
	private JTextField tfPlaca = new JTextField(20);
	private JTextField tfAvarias = new JTextField(20);
	private JTextField tfVeiculoExistente = new JTextField(20);
	
	private JComboBox cbTamanhoVeiculo = new JComboBox(new String[] { "Pequeno", "Medio", "Grande" });
	
	private JPanel cadastroVeiculo;
	private JFrame cadastroVeiculoFrame;

    public void cadastrarVeiculoCliente() {
		
		cadastroVeiculo = new JPanel();
		cadastroVeiculoFrame = new JFrame();
		cadastroVeiculo.setSize(1280, 720);
		//cadastroVeiculo.setLocationRelativeTo(this);
		cadastroVeiculo.setLayout(null);

		cadastroVeiculo.add(lbNome);
		cadastroVeiculo.add(lbCpf);
		cadastroVeiculo.add(tfNome);
		cadastroVeiculo.add(lbEmail);
		cadastroVeiculo.add(lbNumTel);
		cadastroVeiculo.add(tfCpf);
		cadastroVeiculo.add(tfEmail);
		cadastroVeiculo.add(tfNumTel);
		cadastroVeiculo.add(lbModelo);
		cadastroVeiculo.add(lbCor);
		cadastroVeiculo.add(lbPlaca);
		cadastroVeiculo.add(lbTamanho);
		cadastroVeiculo.add(lbAvarias);
		cadastroVeiculo.add(tfModelo);
		cadastroVeiculo.add(tfCor);
		cadastroVeiculo.add(tfPlaca);
		cadastroVeiculo.add(tfAvarias);
		cadastroVeiculo.add(labelDadosPessoais);
		cadastroVeiculo.add(labelDadosVeiculo);
		cadastroVeiculo.add(btCadastrar);
		cadastroVeiculo.add(cbTamanhoVeiculo);
		cadastroVeiculo.add(cbClienteExistente);
		cadastroVeiculo.add(cbVeiculoExistente);
		
		labelDadosPessoais.setFont(new Font("Serif", Font.PLAIN, 20));
		labelDadosPessoais.setBounds(Janela.getLarguraJanela()/2 - 70,50,500,20);
		
		labelDadosVeiculo.setFont(new Font("Serif", Font.PLAIN, 20));
		labelDadosVeiculo.setBounds(Janela.getLarguraJanela()/2 - 70,250,500,20);
		
		//DADOS PESSOAIS//
		lbNome.setBounds(200,100,100,20);
		tfNome.setBounds(285,100,200,20);
		
		lbCpf.setBounds(500,100,100,20);
		tfCpf.setBounds(585,100,200,20);

		lbEmail.setBounds(200,130,100,20);
		tfEmail.setBounds(285,130,200,20);
		
		lbNumTel.setBounds(500,130,100,20);
		tfNumTel.setBounds(585,130,200,20);
		
		cbClienteExistente.setBounds(450,160,200,20);
		lbClienteExiste.setBounds(350,180,200,20);
		tfClienteExistente.setBounds(580,180,200,20);
		btProcuraCliente.setBounds(350,200,200,20);
		lbProcuraCliente.setBounds(580,200,200,20);
		
		//tfCpfClienteExistente.setBounds(200,130,100,20);
		
		//DADOS DO VEICULO//
		lbModelo.setBounds(200, 300,100,20);
		tfModelo.setBounds(285,300,200,20);
		
		lbCor.setBounds(500, 300,200,20);
		tfCor.setBounds(585,300,200,20);
		
		lbPlaca.setBounds(200, 330,100,20);
		tfPlaca.setBounds(285,330,100,20);
		
		lbTamanho.setBounds(500,330,200,20);
		cbTamanhoVeiculo.setBounds(585,330,200,20);
		cbTamanhoVeiculo.setSelectedIndex(0);
		
		lbAvarias.setBounds(200,360,100,20);
		tfAvarias.setBounds(285,360,500,20);
		
		cbVeiculoExistente.setBounds(450,390,500,20);
		lbVeiculoExiste.setBounds(350,420,500,20);
		tfVeiculoExistente.setBounds(580,420,200,20);
		btProcuraVeiculo.setBounds(350,440,200,20);
		lbProcuraVeiculo.setBounds(580,440,200,20);
		
		//BOTOES//
		btCadastrar.setBounds(Janela.getLarguraJanela()/2 - 30, 490,100,50);
		btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	cadastraNovaOcupacao();
            }
        });
		
		cadastroVeiculoFrame.add(cadastroVeiculo);
		cadastroVeiculoFrame.setSize(1280, 720);
		cadastroVeiculoFrame.setVisible(true);
		//add(cadastroVeiculo);
		//encerraMenu();
	}
    
    public void encerraMenu() {
		remove(this);
		this.removeAll();
		this.validate();
		this.repaint();
		updateTela();
	}
    
    public void clienteExistenteActionPerformed() {
		boolean esconderCamposCliente = !cbClienteExistente.isSelected();
		tfNome.setEditable(esconderCamposCliente);
		tfCpf.setEditable(esconderCamposCliente);
		tfNumTel.setEditable(esconderCamposCliente);
		tfEmail.setEditable(esconderCamposCliente);
		
		//Se o checkbox estiver selecionado, adiciono os labels para procurar o cpf do cliente
		if(!esconderCamposCliente) {
			cadastroVeiculo.add(lbClienteExiste);
			cadastroVeiculo.add(tfClienteExistente);
			cadastroVeiculo.add(btProcuraCliente);
			
		} else {
			cadastroVeiculo.remove(lbClienteExiste);
			cadastroVeiculo.remove(tfClienteExistente);
			cadastroVeiculo.remove(btProcuraCliente);
			cadastroVeiculo.remove(lbProcuraCliente);
		}
		cadastroVeiculo.updateUI();
	}
    
    public void veiculoExistenteActionPerformed() {
		boolean esconderCamposVeiculo = !cbVeiculoExistente.isSelected();
		cbTamanhoVeiculo.setEditable(esconderCamposVeiculo);
		tfAvarias.setEditable(esconderCamposVeiculo);
		tfPlaca.setEditable(esconderCamposVeiculo);
		tfModelo.setEditable(esconderCamposVeiculo);
		tfAvarias.setEditable(esconderCamposVeiculo);
		tfCor.setEditable(esconderCamposVeiculo);
		if(!esconderCamposVeiculo) {
			cadastroVeiculo.add(lbVeiculoExiste);
			cadastroVeiculo.add(tfVeiculoExistente);
			cadastroVeiculo.add(btProcuraVeiculo);
		} else {
			cadastroVeiculo.remove(lbVeiculoExiste);
			cadastroVeiculo.remove(tfVeiculoExistente);
			cadastroVeiculo.remove(btProcuraVeiculo);
			cadastroVeiculo.remove(lbProcuraVeiculo);
		}
		cadastroVeiculo.updateUI();
	}
    
    public void procuraClienteExistente() {
		gerenciador.cadastraNovoCliente("", "123", "", "");
		Cliente cliente = gerenciador.getCliente(tfClienteExistente.getText());
		String confirmacao;
		if(cliente != null) {
			confirmacao = "Cliente achado";
		} else {
			confirmacao = "Cliente não cadastrado";
		}
		lbProcuraCliente.setText(confirmacao);
		cadastroVeiculo.add(lbProcuraCliente);
		cadastroVeiculo.updateUI();
	}
    
    public void procuraVeiculoExistente() {
		Veiculo veiculo = gerenciador.getVeiculo(tfVeiculoExistente.getText());
		String confirmacao;
		if(veiculo != null) {
			confirmacao = "Veiculo achado";
		} else {
			confirmacao = "Veiculo não cadastrado";
		}
		lbProcuraVeiculo.setText(confirmacao);
		cadastroVeiculo.add(lbProcuraVeiculo);
		cadastroVeiculo.updateUI();
	}
    
    public void cadastraNovaOcupacao() {
		Cliente cliente;
		if(cbClienteExistente.isSelected())
			cliente = gerenciador.cadastraNovoCliente(tfNome.getText(), tfCpf.getText(), tfNumTel.getText(),
					tfEmail.getText());
		else 
			cliente = gerenciador.getCliente(tfCpfClienteExistente.getText());
		
		tfNome.setEditable(false);
		Veiculo veiculo = gerenciador.cadastraNovoVeiculo(tfModelo.getText(), tfPlaca.getText(), tfCor.getText(),
				cbTamanhoVeiculo.getSelectedItem().toString(), tfAvarias.getText());
		gerenciador.novaOcupacao(cliente, veiculo);
		gerenciador.salvaBancoDeDados();

	}
    
    public void updateTela() {
		setTitle("Estacionamento"); // TÍTULO DA JANELA
		setDefaultCloseOperation(3); // OPERAÇÕES DA JANELA, MAXIMIZAR, MINIMIZAR E FECHA;
		setSize(larguraJanela,alturaJanela); // DEFINE O TAMANHO DA JANELA;
		setLocationRelativeTo(null);
		setResizable(false);
		setVisible(true);
	}
    

}
